# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QMessageBox
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score, fbeta_score
from sklearn.model_selection import cross_val_score, KFold
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler
import numpy as np
import os

class Sorular(object):
    def setupUi(self, Dialog, clf):
        self.answers = np.zeros(18, dtype=int)
        self.likert_scale = {"Hiç katılmıyorum": 1, "Katılmıyorum": 2, "Kararsızım": 3, "Katılıyorum": 4, "Kesinlikle katılıyorum": 5}
        self.clf = clf
        
        Dialog.setObjectName("Dialog")
        Dialog.resize(651, 789)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 571, 731))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.cevap3 = QtWidgets.QGroupBox(self.frame)
        self.cevap3.setGeometry(QtCore.QRect(20, 190, 531, 41))
        self.cevap3.setTitle("")
        self.cevap3.setObjectName("cevap3")
        self.radioButton_136 = QtWidgets.QRadioButton(self.cevap3)
        self.radioButton_136.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_136.setObjectName("radioButton_136")
        self.radioButton_137 = QtWidgets.QRadioButton(self.cevap3)
        self.radioButton_137.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_137.setObjectName("radioButton_137")
        self.radioButton_138 = QtWidgets.QRadioButton(self.cevap3)
        self.radioButton_138.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_138.setObjectName("radioButton_138")
        self.radioButton_139 = QtWidgets.QRadioButton(self.cevap3)
        self.radioButton_139.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_139.setObjectName("radioButton_139")
        self.radioButton_140 = QtWidgets.QRadioButton(self.cevap3)
        self.radioButton_140.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_140.setObjectName("radioButton_140")
        self.cevap5 = QtWidgets.QGroupBox(self.frame)
        self.cevap5.setGeometry(QtCore.QRect(20, 360, 531, 41))
        self.cevap5.setTitle("")
        self.cevap5.setObjectName("cevap5")
        self.radioButton_141 = QtWidgets.QRadioButton(self.cevap5)
        self.radioButton_141.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_141.setObjectName("radioButton_141")
        self.radioButton_142 = QtWidgets.QRadioButton(self.cevap5)
        self.radioButton_142.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_142.setObjectName("radioButton_142")
        self.radioButton_143 = QtWidgets.QRadioButton(self.cevap5)
        self.radioButton_143.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_143.setObjectName("radioButton_143")
        self.radioButton_144 = QtWidgets.QRadioButton(self.cevap5)
        self.radioButton_144.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_144.setObjectName("radioButton_144")
        self.radioButton_145 = QtWidgets.QRadioButton(self.cevap5)
        self.radioButton_145.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_145.setObjectName("radioButton_145")
        self.cevap7 = QtWidgets.QGroupBox(self.frame)
        self.cevap7.setGeometry(QtCore.QRect(20, 520, 531, 41))
        self.cevap7.setTitle("")
        self.cevap7.setObjectName("cevap7")
        self.radioButton_146 = QtWidgets.QRadioButton(self.cevap7)
        self.radioButton_146.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_146.setObjectName("radioButton_146")
        self.radioButton_147 = QtWidgets.QRadioButton(self.cevap7)
        self.radioButton_147.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_147.setObjectName("radioButton_147")
        self.radioButton_148 = QtWidgets.QRadioButton(self.cevap7)
        self.radioButton_148.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_148.setObjectName("radioButton_148")
        self.radioButton_149 = QtWidgets.QRadioButton(self.cevap7)
        self.radioButton_149.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_149.setObjectName("radioButton_149")
        self.radioButton_150 = QtWidgets.QRadioButton(self.cevap7)
        self.radioButton_150.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_150.setObjectName("radioButton_150")
        self.cevap6 = QtWidgets.QGroupBox(self.frame)
        self.cevap6.setGeometry(QtCore.QRect(20, 440, 531, 41))
        self.cevap6.setTitle("")
        self.cevap6.setObjectName("cevap6")
        self.radioButton_151 = QtWidgets.QRadioButton(self.cevap6)
        self.radioButton_151.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_151.setObjectName("radioButton_151")
        self.radioButton_152 = QtWidgets.QRadioButton(self.cevap6)
        self.radioButton_152.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_152.setObjectName("radioButton_152")
        self.radioButton_153 = QtWidgets.QRadioButton(self.cevap6)
        self.radioButton_153.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_153.setObjectName("radioButton_153")
        self.radioButton_154 = QtWidgets.QRadioButton(self.cevap6)
        self.radioButton_154.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_154.setObjectName("radioButton_154")
        self.radioButton_155 = QtWidgets.QRadioButton(self.cevap6)
        self.radioButton_155.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_155.setObjectName("radioButton_155")
        self.soru9 = QtWidgets.QLabel(self.frame)
        self.soru9.setGeometry(QtCore.QRect(20, 660, 461, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru9.setFont(font)
        self.soru9.setObjectName("soru9")
        self.soru7 = QtWidgets.QLabel(self.frame)
        self.soru7.setGeometry(QtCore.QRect(20, 500, 461, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru7.setFont(font)
        self.soru7.setObjectName("soru7")
        self.cevap8 = QtWidgets.QGroupBox(self.frame)
        self.cevap8.setGeometry(QtCore.QRect(20, 600, 531, 41))
        self.cevap8.setTitle("")
        self.cevap8.setObjectName("cevap8")
        self.radioButton_156 = QtWidgets.QRadioButton(self.cevap8)
        self.radioButton_156.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_156.setObjectName("radioButton_156")
        self.radioButton_157 = QtWidgets.QRadioButton(self.cevap8)
        self.radioButton_157.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_157.setObjectName("radioButton_157")
        self.radioButton_158 = QtWidgets.QRadioButton(self.cevap8)
        self.radioButton_158.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_158.setObjectName("radioButton_158")
        self.radioButton_159 = QtWidgets.QRadioButton(self.cevap8)
        self.radioButton_159.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_159.setObjectName("radioButton_159")
        self.radioButton_160 = QtWidgets.QRadioButton(self.cevap8)
        self.radioButton_160.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_160.setObjectName("radioButton_160")
        self.soru4 = QtWidgets.QLabel(self.frame)
        self.soru4.setGeometry(QtCore.QRect(20, 230, 531, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru4.setFont(font)
        self.soru4.setObjectName("soru4")
        self.soru8 = QtWidgets.QLabel(self.frame)
        self.soru8.setGeometry(QtCore.QRect(20, 580, 491, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru8.setFont(font)
        self.soru8.setObjectName("soru8")
        self.cevap2 = QtWidgets.QGroupBox(self.frame)
        self.cevap2.setGeometry(QtCore.QRect(20, 110, 531, 41))
        self.cevap2.setTitle("")
        self.cevap2.setObjectName("cevap2")
        self.radioButton_161 = QtWidgets.QRadioButton(self.cevap2)
        self.radioButton_161.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_161.setObjectName("radioButton_161")
        self.radioButton_162 = QtWidgets.QRadioButton(self.cevap2)
        self.radioButton_162.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_162.setObjectName("radioButton_162")
        self.radioButton_163 = QtWidgets.QRadioButton(self.cevap2)
        self.radioButton_163.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_163.setObjectName("radioButton_163")
        self.radioButton_164 = QtWidgets.QRadioButton(self.cevap2)
        self.radioButton_164.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_164.setObjectName("radioButton_164")
        self.radioButton_165 = QtWidgets.QRadioButton(self.cevap2)
        self.radioButton_165.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_165.setObjectName("radioButton_165")
        self.soru5 = QtWidgets.QLabel(self.frame)
        self.soru5.setGeometry(QtCore.QRect(20, 340, 481, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru5.setFont(font)
        self.soru5.setObjectName("soru5")
        self.cevap1 = QtWidgets.QGroupBox(self.frame)
        self.cevap1.setGeometry(QtCore.QRect(20, 30, 531, 41))
        self.cevap1.setTitle("")
        self.cevap1.setObjectName("cevap1")
        self.radioButton_166 = QtWidgets.QRadioButton(self.cevap1)
        self.radioButton_166.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_166.setObjectName("radioButton_166")
        self.radioButton_167 = QtWidgets.QRadioButton(self.cevap1)
        self.radioButton_167.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_167.setObjectName("radioButton_167")
        self.radioButton_168 = QtWidgets.QRadioButton(self.cevap1)
        self.radioButton_168.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_168.setObjectName("radioButton_168")
        self.radioButton_169 = QtWidgets.QRadioButton(self.cevap1)
        self.radioButton_169.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_169.setObjectName("radioButton_169")
        self.radioButton_170 = QtWidgets.QRadioButton(self.cevap1)
        self.radioButton_170.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_170.setObjectName("radioButton_170")
        self.cevap4 = QtWidgets.QGroupBox(self.frame)
        self.cevap4.setGeometry(QtCore.QRect(20, 280, 531, 41))
        self.cevap4.setTitle("")
        self.cevap4.setObjectName("cevap4")
        self.radioButton_171 = QtWidgets.QRadioButton(self.cevap4)
        self.radioButton_171.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_171.setObjectName("radioButton_171")
        self.radioButton_172 = QtWidgets.QRadioButton(self.cevap4)
        self.radioButton_172.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_172.setObjectName("radioButton_172")
        self.radioButton_173 = QtWidgets.QRadioButton(self.cevap4)
        self.radioButton_173.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_173.setObjectName("radioButton_173")
        self.radioButton_174 = QtWidgets.QRadioButton(self.cevap4)
        self.radioButton_174.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_174.setObjectName("radioButton_174")
        self.radioButton_175 = QtWidgets.QRadioButton(self.cevap4)
        self.radioButton_175.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_175.setObjectName("radioButton_175")
        self.soru6 = QtWidgets.QLabel(self.frame)
        self.soru6.setGeometry(QtCore.QRect(20, 420, 461, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru6.setFont(font)
        self.soru6.setObjectName("soru6")
        self.cevap9 = QtWidgets.QGroupBox(self.frame)
        self.cevap9.setGeometry(QtCore.QRect(20, 680, 531, 41))
        self.cevap9.setTitle("")
        self.cevap9.setObjectName("cevap9")
        self.radioButton_176 = QtWidgets.QRadioButton(self.cevap9)
        self.radioButton_176.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_176.setObjectName("radioButton_176")
        self.radioButton_177 = QtWidgets.QRadioButton(self.cevap9)
        self.radioButton_177.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_177.setObjectName("radioButton_177")
        self.radioButton_178 = QtWidgets.QRadioButton(self.cevap9)
        self.radioButton_178.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_178.setObjectName("radioButton_178")
        self.radioButton_179 = QtWidgets.QRadioButton(self.cevap9)
        self.radioButton_179.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_179.setObjectName("radioButton_179")
        self.radioButton_180 = QtWidgets.QRadioButton(self.cevap9)
        self.radioButton_180.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_180.setObjectName("radioButton_180")
        self.soru2 = QtWidgets.QLabel(self.frame)
        self.soru2.setGeometry(QtCore.QRect(20, 90, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru2.setFont(font)
        self.soru2.setObjectName("soru2")
        self.soru3 = QtWidgets.QLabel(self.frame)
        self.soru3.setGeometry(QtCore.QRect(20, 170, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru3.setFont(font)
        self.soru3.setObjectName("soru3")
        self.soru1 = QtWidgets.QLabel(self.frame)
        self.soru1.setGeometry(QtCore.QRect(20, 10, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru1.setFont(font)
        self.soru1.setObjectName("soru1")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 621, 731))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.cevap12 = QtWidgets.QGroupBox(self.frame_2)
        self.cevap12.setGeometry(QtCore.QRect(20, 190, 531, 41))
        self.cevap12.setTitle("")
        self.cevap12.setObjectName("cevap12")
        self.radioButton_181 = QtWidgets.QRadioButton(self.cevap12)
        self.radioButton_181.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_181.setObjectName("radioButton_181")
        self.radioButton_182 = QtWidgets.QRadioButton(self.cevap12)
        self.radioButton_182.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_182.setObjectName("radioButton_182")
        self.radioButton_183 = QtWidgets.QRadioButton(self.cevap12)
        self.radioButton_183.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_183.setObjectName("radioButton_183")
        self.radioButton_184 = QtWidgets.QRadioButton(self.cevap12)
        self.radioButton_184.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_184.setObjectName("radioButton_184")
        self.radioButton_185 = QtWidgets.QRadioButton(self.cevap12)
        self.radioButton_185.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_185.setObjectName("radioButton_185")
        self.cevap14 = QtWidgets.QGroupBox(self.frame_2)
        self.cevap14.setGeometry(QtCore.QRect(20, 360, 531, 41))
        self.cevap14.setTitle("")
        self.cevap14.setObjectName("cevap14")
        self.radioButton_186 = QtWidgets.QRadioButton(self.cevap14)
        self.radioButton_186.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_186.setObjectName("radioButton_186")
        self.radioButton_187 = QtWidgets.QRadioButton(self.cevap14)
        self.radioButton_187.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_187.setObjectName("radioButton_187")
        self.radioButton_188 = QtWidgets.QRadioButton(self.cevap14)
        self.radioButton_188.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_188.setObjectName("radioButton_188")
        self.radioButton_189 = QtWidgets.QRadioButton(self.cevap14)
        self.radioButton_189.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_189.setObjectName("radioButton_189")
        self.radioButton_190 = QtWidgets.QRadioButton(self.cevap14)
        self.radioButton_190.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_190.setObjectName("radioButton_190")
        self.cevap16 = QtWidgets.QGroupBox(self.frame_2)
        self.cevap16.setGeometry(QtCore.QRect(20, 520, 531, 41))
        self.cevap16.setTitle("")
        self.cevap16.setObjectName("cevap16")
        self.radioButton_191 = QtWidgets.QRadioButton(self.cevap16)
        self.radioButton_191.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_191.setObjectName("radioButton_191")
        self.radioButton_192 = QtWidgets.QRadioButton(self.cevap16)
        self.radioButton_192.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_192.setObjectName("radioButton_192")
        self.radioButton_193 = QtWidgets.QRadioButton(self.cevap16)
        self.radioButton_193.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_193.setObjectName("radioButton_193")
        self.radioButton_194 = QtWidgets.QRadioButton(self.cevap16)
        self.radioButton_194.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_194.setObjectName("radioButton_194")
        self.radioButton_195 = QtWidgets.QRadioButton(self.cevap16)
        self.radioButton_195.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_195.setObjectName("radioButton_195")
        self.cevap15 = QtWidgets.QGroupBox(self.frame_2)
        self.cevap15.setGeometry(QtCore.QRect(20, 440, 531, 41))
        self.cevap15.setTitle("")
        self.cevap15.setObjectName("cevap15")
        self.radioButton_196 = QtWidgets.QRadioButton(self.cevap15)
        self.radioButton_196.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_196.setObjectName("radioButton_196")
        self.radioButton_197 = QtWidgets.QRadioButton(self.cevap15)
        self.radioButton_197.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_197.setObjectName("radioButton_197")
        self.radioButton_198 = QtWidgets.QRadioButton(self.cevap15)
        self.radioButton_198.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_198.setObjectName("radioButton_198")
        self.radioButton_199 = QtWidgets.QRadioButton(self.cevap15)
        self.radioButton_199.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_199.setObjectName("radioButton_199")
        self.radioButton_200 = QtWidgets.QRadioButton(self.cevap15)
        self.radioButton_200.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_200.setObjectName("radioButton_200")
        self.soru18 = QtWidgets.QLabel(self.frame_2)
        self.soru18.setGeometry(QtCore.QRect(20, 660, 461, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru18.setFont(font)
        self.soru18.setObjectName("soru18")
        self.soru16 = QtWidgets.QLabel(self.frame_2)
        self.soru16.setGeometry(QtCore.QRect(20, 500, 511, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru16.setFont(font)
        self.soru16.setObjectName("soru16")
        self.cevap17 = QtWidgets.QGroupBox(self.frame_2)
        self.cevap17.setGeometry(QtCore.QRect(20, 600, 531, 41))
        self.cevap17.setTitle("")
        self.cevap17.setObjectName("cevap17")
        self.radioButton_201 = QtWidgets.QRadioButton(self.cevap17)
        self.radioButton_201.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_201.setObjectName("radioButton_201")
        self.radioButton_202 = QtWidgets.QRadioButton(self.cevap17)
        self.radioButton_202.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_202.setObjectName("radioButton_202")
        self.radioButton_203 = QtWidgets.QRadioButton(self.cevap17)
        self.radioButton_203.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_203.setObjectName("radioButton_203")
        self.radioButton_204 = QtWidgets.QRadioButton(self.cevap17)
        self.radioButton_204.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_204.setObjectName("radioButton_204")
        self.radioButton_205 = QtWidgets.QRadioButton(self.cevap17)
        self.radioButton_205.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_205.setObjectName("radioButton_205")
        self.soru13 = QtWidgets.QLabel(self.frame_2)
        self.soru13.setGeometry(QtCore.QRect(20, 230, 561, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru13.setFont(font)
        self.soru13.setObjectName("soru13")
        self.soru17 = QtWidgets.QLabel(self.frame_2)
        self.soru17.setGeometry(QtCore.QRect(20, 580, 491, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru17.setFont(font)
        self.soru17.setObjectName("soru17")
        self.cevap11 = QtWidgets.QGroupBox(self.frame_2)
        self.cevap11.setGeometry(QtCore.QRect(20, 110, 531, 41))
        self.cevap11.setTitle("")
        self.cevap11.setObjectName("cevap11")
        self.radioButton_206 = QtWidgets.QRadioButton(self.cevap11)
        self.radioButton_206.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_206.setObjectName("radioButton_206")
        self.radioButton_207 = QtWidgets.QRadioButton(self.cevap11)
        self.radioButton_207.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_207.setObjectName("radioButton_207")
        self.radioButton_208 = QtWidgets.QRadioButton(self.cevap11)
        self.radioButton_208.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_208.setObjectName("radioButton_208")
        self.radioButton_209 = QtWidgets.QRadioButton(self.cevap11)
        self.radioButton_209.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_209.setObjectName("radioButton_209")
        self.radioButton_210 = QtWidgets.QRadioButton(self.cevap11)
        self.radioButton_210.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_210.setObjectName("radioButton_210")
        self.soru14 = QtWidgets.QLabel(self.frame_2)
        self.soru14.setGeometry(QtCore.QRect(20, 340, 581, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru14.setFont(font)
        self.soru14.setObjectName("soru14")
        self.cevap10 = QtWidgets.QGroupBox(self.frame_2)
        self.cevap10.setGeometry(QtCore.QRect(20, 30, 531, 41))
        self.cevap10.setTitle("")
        self.cevap10.setObjectName("cevap10")
        self.radioButton_211 = QtWidgets.QRadioButton(self.cevap10)
        self.radioButton_211.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_211.setObjectName("radioButton_211")
        self.radioButton_212 = QtWidgets.QRadioButton(self.cevap10)
        self.radioButton_212.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_212.setObjectName("radioButton_212")
        self.radioButton_213 = QtWidgets.QRadioButton(self.cevap10)
        self.radioButton_213.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_213.setObjectName("radioButton_213")
        self.radioButton_214 = QtWidgets.QRadioButton(self.cevap10)
        self.radioButton_214.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_214.setObjectName("radioButton_214")
        self.radioButton_215 = QtWidgets.QRadioButton(self.cevap10)
        self.radioButton_215.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_215.setObjectName("radioButton_215")
        self.cevap13 = QtWidgets.QGroupBox(self.frame_2)
        self.cevap13.setGeometry(QtCore.QRect(20, 280, 531, 41))
        self.cevap13.setTitle("")
        self.cevap13.setObjectName("cevap13")
        self.radioButton_216 = QtWidgets.QRadioButton(self.cevap13)
        self.radioButton_216.setGeometry(QtCore.QRect(10, 10, 101, 17))
        self.radioButton_216.setObjectName("radioButton_216")
        self.radioButton_217 = QtWidgets.QRadioButton(self.cevap13)
        self.radioButton_217.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_217.setObjectName("radioButton_217")
        self.radioButton_218 = QtWidgets.QRadioButton(self.cevap13)
        self.radioButton_218.setGeometry(QtCore.QRect(230, 10, 82, 17))
        self.radioButton_218.setObjectName("radioButton_218")
        self.radioButton_219 = QtWidgets.QRadioButton(self.cevap13)
        self.radioButton_219.setGeometry(QtCore.QRect(320, 10, 82, 17))
        self.radioButton_219.setObjectName("radioButton_219")
        self.radioButton_220 = QtWidgets.QRadioButton(self.cevap13)
        self.radioButton_220.setGeometry(QtCore.QRect(410, 10, 121, 17))
        self.radioButton_220.setObjectName("radioButton_220")
        self.soru15 = QtWidgets.QLabel(self.frame_2)
        self.soru15.setGeometry(QtCore.QRect(20, 420, 501, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru15.setFont(font)
        self.soru15.setObjectName("soru15")
        self.soru11 = QtWidgets.QLabel(self.frame_2)
        self.soru11.setGeometry(QtCore.QRect(20, 90, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru11.setFont(font)
        self.soru11.setObjectName("soru11")
        self.soru12 = QtWidgets.QLabel(self.frame_2)
        self.soru12.setGeometry(QtCore.QRect(20, 170, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru12.setFont(font)
        self.soru12.setObjectName("soru12")
        self.soru10 = QtWidgets.QLabel(self.frame_2)
        self.soru10.setGeometry(QtCore.QRect(20, 0, 611, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soru10.setFont(font)
        self.soru10.setObjectName("soru10")
        self.cevap18 = QtWidgets.QLineEdit(self.frame_2)
        self.cevap18.setGeometry(QtCore.QRect(20, 690, 131, 20))
        self.cevap18.setObjectName("cevap18")
        self.diger_sayfa = QtWidgets.QPushButton(Dialog)
        self.diger_sayfa.setGeometry(QtCore.QRect(240, 750, 131, 23))
        self.diger_sayfa.setObjectName("diger_sayfa")
        self.diger_sayfa.clicked.connect(self.turn_page)

        self.testi_bitir = QtWidgets.QPushButton(Dialog)
        self.testi_bitir.setGeometry(QtCore.QRect(240, 750, 131, 23))
        self.testi_bitir.setObjectName("testi_bitir")
        self.testi_bitir.setVisible(False)
        self.testi_bitir.clicked.connect(self.save_answers)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.frame_2.setVisible(False)


    def answer_changed(self, selected_button):
        if selected_button.isChecked():
            print("Seçilen düğme:", selected_button.text())
            print("Seçilen parent:", selected_button.parent().objectName())
            question_number = int(selected_button.parent().objectName()[5:])
            self.answers[question_number - 1] = int(self.likert_scale[selected_button.text()])

    def save_answers(self):
        vector_class = FeatureVectorCalculations(self.answers)
        feature_vector = vector_class.get_hash_table()
        feature_vector = [feature_vector]
        pred = self.clf.predict(feature_vector)
        self.show_credit_risk(pred)

    def show_credit_risk(self, pred):
        new_window = QMainWindow()
        new_window.setWindowTitle("Yeni Pencere")
        new_window.setGeometry(730, 480, 548, 50)
        message_box = QMessageBox(new_window)
        message_box.setStyleSheet("padding-right: 20px")

        if pred == 0:
            message_box.setText("Kredi riski düşük")
        else:
            message_box.setText("Kredi riski yüksek")

        message_box.exec_()


    def setModel(self, clf):
        self.clf = clf

    def turn_page(self):
        self.diger_sayfa.setVisible(False)
        self.testi_bitir.setVisible(True)
        self.frame.setVisible(False)
        self.frame_2.setVisible(True)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton_136.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_137.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_138.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_139.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_140.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.radioButton_141.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_142.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_143.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_144.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_145.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.radioButton_146.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_147.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_148.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_149.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_150.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.radioButton_151.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_152.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_153.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_154.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_155.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.soru9.setText(_translate("Dialog", "Sinirlendiğimde çevreme zarar verdiğim zamanlar olmuştur."))
        self.soru7.setText(_translate("Dialog", "Hedeflerime bağlı kalmak ve onlara ulaşmak benim için kolaydır."))
        self.radioButton_156.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_157.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_158.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_159.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_160.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.soru4.setText(_translate("Dialog", "<html><head/><body><p>Eğer beklenmeyen bir masrafla (örneğin çamaşır makinesinin bozulması gibi) karşılaşırsam<br>bunu karşılayacak kadar birikimim bulunuyor.</p></body></html>"))
        self.soru8.setText(_translate("Dialog", "Diğer insanların maddi imkanlarının daha iyi olmasına özendiğim zamanlar olmuştur."))
        self.radioButton_161.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_162.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_163.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_164.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_165.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.soru5.setText(_translate("Dialog", "Bugünün toplumunda, bir kişinin borçları olmadan yaşaması neredeyse imkansızdır."))
        self.radioButton_166.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_167.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_168.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_169.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_170.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.radioButton_171.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_172.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_173.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_174.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_175.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.soru6.setText(_translate("Dialog", "Rahatlığım, aldığım kararlar ve gerçekleştirdiğim eylemlerde büyük bir etkendir."))
        self.radioButton_176.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_177.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_178.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_179.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_180.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.soru2.setText(_translate("Dialog", "Borç birçok insan için hayatın normal bir parçasıdır."))
        self.soru3.setText(_translate("Dialog", "Pahalı evleri, arabaları ve kıyafetleri olan insanlara hayranım."))
        self.soru1.setText(_translate("Dialog", "Bir sorunla karşılaştığımda, genellikle birkaç çözüm üretebilirim."))
        self.radioButton_181.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_182.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_183.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_184.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_185.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.radioButton_186.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_187.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_188.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_189.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_190.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.radioButton_191.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_192.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_193.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_194.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_195.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.radioButton_196.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_197.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_198.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_199.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_200.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.soru18.setText(_translate("Dialog", "Yaşınız nedir?"))
        self.soru16.setText(_translate("Dialog", "İnsanları etkileyen şeylere sahip olmayı seviyorum."))
        self.radioButton_201.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_202.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_203.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_204.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_205.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.soru13.setText(_translate("Dialog", "<html><head/><body><p>Gelecekteki problemler hakkında düşünmüyorum, çünkü bu problemlerin kendiliğinden<br>çözümleneceğini düşünüyorum.</p></body></html>"))
        self.soru17.setText(_translate("Dialog", "İnsanların başarılarını gösteren maddi varlıkların miktarına büyük önem veririm."))
        self.radioButton_206.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_207.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_208.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_209.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_210.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.soru14.setText(_translate("Dialog", "Sorunlarım olduğunda sakin kalabilirim, çünkü sorunlarla başa çıkma konusunda kendime güvenirim."))
        self.radioButton_211.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_212.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_213.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_214.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_215.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.radioButton_216.setText(_translate("Dialog", "Hiç katılmıyorum"))
        self.radioButton_217.setText(_translate("Dialog", "Katılmıyorum"))
        self.radioButton_218.setText(_translate("Dialog", "Kararsızım"))
        self.radioButton_219.setText(_translate("Dialog", "Katılıyorum"))
        self.radioButton_220.setText(_translate("Dialog", "Kesinlikle katılıyorum"))
        self.soru15.setText(_translate("Dialog", "İnsanların hayattan zevk almasına yardımcı oluyorsa, kredi kullanmak iyi bir şey olabilir."))
        self.soru11.setText(_translate("Dialog", "İstediğim şeyler olmadığında bazen çabuk kızarım."))
        self.soru12.setText(_translate("Dialog", "Bazen faturalarımı zamanında ödemeyi unutuyorum."))
        self.soru10.setText(_translate("Dialog", "Anlık isteklerime göre hareket ederim, geleceğin nasıl olacağı veya ne getireceği üzerine çok düşünmem."))
        self.diger_sayfa.setText(_translate("Dialog", "Diğer Sayfa"))
        
        self.radioButton_136.toggled.connect(lambda: self.answer_changed(self.radioButton_136))
        self.radioButton_137.toggled.connect(lambda: self.answer_changed(self.radioButton_137))
        self.radioButton_138.toggled.connect(lambda: self.answer_changed(self.radioButton_138))
        self.radioButton_139.toggled.connect(lambda: self.answer_changed(self.radioButton_139))
        self.radioButton_140.toggled.connect(lambda: self.answer_changed(self.radioButton_140))
        self.radioButton_141.toggled.connect(lambda: self.answer_changed(self.radioButton_141))
        self.radioButton_142.toggled.connect(lambda: self.answer_changed(self.radioButton_142))
        self.radioButton_143.toggled.connect(lambda: self.answer_changed(self.radioButton_143))
        self.radioButton_144.toggled.connect(lambda: self.answer_changed(self.radioButton_144))
        self.radioButton_145.toggled.connect(lambda: self.answer_changed(self.radioButton_145))
        self.radioButton_146.toggled.connect(lambda: self.answer_changed(self.radioButton_146))
        self.radioButton_147.toggled.connect(lambda: self.answer_changed(self.radioButton_147))
        self.radioButton_148.toggled.connect(lambda: self.answer_changed(self.radioButton_148))
        self.radioButton_149.toggled.connect(lambda: self.answer_changed(self.radioButton_149))
        self.radioButton_150.toggled.connect(lambda: self.answer_changed(self.radioButton_150))
        self.radioButton_151.toggled.connect(lambda: self.answer_changed(self.radioButton_151))
        self.radioButton_152.toggled.connect(lambda: self.answer_changed(self.radioButton_152))
        self.radioButton_153.toggled.connect(lambda: self.answer_changed(self.radioButton_153))
        self.radioButton_154.toggled.connect(lambda: self.answer_changed(self.radioButton_154))
        self.radioButton_155.toggled.connect(lambda: self.answer_changed(self.radioButton_155))
        self.radioButton_156.toggled.connect(lambda: self.answer_changed(self.radioButton_156))
        self.radioButton_157.toggled.connect(lambda: self.answer_changed(self.radioButton_157))
        self.radioButton_158.toggled.connect(lambda: self.answer_changed(self.radioButton_158))
        self.radioButton_159.toggled.connect(lambda: self.answer_changed(self.radioButton_159))
        self.radioButton_160.toggled.connect(lambda: self.answer_changed(self.radioButton_160))
        self.radioButton_161.toggled.connect(lambda: self.answer_changed(self.radioButton_161))
        self.radioButton_162.toggled.connect(lambda: self.answer_changed(self.radioButton_162))
        self.radioButton_163.toggled.connect(lambda: self.answer_changed(self.radioButton_163))
        self.radioButton_164.toggled.connect(lambda: self.answer_changed(self.radioButton_164))
        self.radioButton_165.toggled.connect(lambda: self.answer_changed(self.radioButton_165))
        self.radioButton_166.toggled.connect(lambda: self.answer_changed(self.radioButton_166))
        self.radioButton_167.toggled.connect(lambda: self.answer_changed(self.radioButton_167))
        self.radioButton_168.toggled.connect(lambda: self.answer_changed(self.radioButton_168))
        self.radioButton_169.toggled.connect(lambda: self.answer_changed(self.radioButton_169))
        self.radioButton_170.toggled.connect(lambda: self.answer_changed(self.radioButton_170))
        self.radioButton_171.toggled.connect(lambda: self.answer_changed(self.radioButton_171))
        self.radioButton_172.toggled.connect(lambda: self.answer_changed(self.radioButton_172))
        self.radioButton_173.toggled.connect(lambda: self.answer_changed(self.radioButton_173))
        self.radioButton_174.toggled.connect(lambda: self.answer_changed(self.radioButton_174))
        self.radioButton_175.toggled.connect(lambda: self.answer_changed(self.radioButton_175))
        self.radioButton_176.toggled.connect(lambda: self.answer_changed(self.radioButton_176))
        self.radioButton_177.toggled.connect(lambda: self.answer_changed(self.radioButton_177))
        self.radioButton_178.toggled.connect(lambda: self.answer_changed(self.radioButton_178))
        self.radioButton_179.toggled.connect(lambda: self.answer_changed(self.radioButton_179))
        self.radioButton_180.toggled.connect(lambda: self.answer_changed(self.radioButton_180))
        self.radioButton_181.toggled.connect(lambda: self.answer_changed(self.radioButton_181))
        self.radioButton_182.toggled.connect(lambda: self.answer_changed(self.radioButton_182))
        self.radioButton_183.toggled.connect(lambda: self.answer_changed(self.radioButton_183))
        self.radioButton_184.toggled.connect(lambda: self.answer_changed(self.radioButton_184))
        self.radioButton_185.toggled.connect(lambda: self.answer_changed(self.radioButton_185))
        self.radioButton_186.toggled.connect(lambda: self.answer_changed(self.radioButton_186))
        self.radioButton_187.toggled.connect(lambda: self.answer_changed(self.radioButton_187))
        self.radioButton_188.toggled.connect(lambda: self.answer_changed(self.radioButton_188))
        self.radioButton_189.toggled.connect(lambda: self.answer_changed(self.radioButton_189))
        self.radioButton_190.toggled.connect(lambda: self.answer_changed(self.radioButton_190))
        self.radioButton_191.toggled.connect(lambda: self.answer_changed(self.radioButton_191))
        self.radioButton_192.toggled.connect(lambda: self.answer_changed(self.radioButton_192))
        self.radioButton_193.toggled.connect(lambda: self.answer_changed(self.radioButton_193))
        self.radioButton_194.toggled.connect(lambda: self.answer_changed(self.radioButton_194))
        self.radioButton_195.toggled.connect(lambda: self.answer_changed(self.radioButton_195))
        self.radioButton_196.toggled.connect(lambda: self.answer_changed(self.radioButton_196))
        self.radioButton_197.toggled.connect(lambda: self.answer_changed(self.radioButton_197))
        self.radioButton_198.toggled.connect(lambda: self.answer_changed(self.radioButton_198))
        self.radioButton_199.toggled.connect(lambda: self.answer_changed(self.radioButton_199))
        self.radioButton_200.toggled.connect(lambda: self.answer_changed(self.radioButton_200))
        self.radioButton_201.toggled.connect(lambda: self.answer_changed(self.radioButton_201))
        self.radioButton_202.toggled.connect(lambda: self.answer_changed(self.radioButton_202))
        self.radioButton_203.toggled.connect(lambda: self.answer_changed(self.radioButton_203))
        self.radioButton_204.toggled.connect(lambda: self.answer_changed(self.radioButton_204))
        self.radioButton_205.toggled.connect(lambda: self.answer_changed(self.radioButton_205))
        self.radioButton_206.toggled.connect(lambda: self.answer_changed(self.radioButton_206))
        self.radioButton_207.toggled.connect(lambda: self.answer_changed(self.radioButton_207))
        self.radioButton_208.toggled.connect(lambda: self.answer_changed(self.radioButton_208))
        self.radioButton_209.toggled.connect(lambda: self.answer_changed(self.radioButton_209))
        self.radioButton_210.toggled.connect(lambda: self.answer_changed(self.radioButton_210))
        self.radioButton_211.toggled.connect(lambda: self.answer_changed(self.radioButton_211))
        self.radioButton_212.toggled.connect(lambda: self.answer_changed(self.radioButton_212))
        self.radioButton_213.toggled.connect(lambda: self.answer_changed(self.radioButton_213))
        self.radioButton_214.toggled.connect(lambda: self.answer_changed(self.radioButton_214))
        self.radioButton_215.toggled.connect(lambda: self.answer_changed(self.radioButton_215))
        self.radioButton_216.toggled.connect(lambda: self.answer_changed(self.radioButton_216))
        self.radioButton_217.toggled.connect(lambda: self.answer_changed(self.radioButton_217))
        self.radioButton_218.toggled.connect(lambda: self.answer_changed(self.radioButton_218))
        self.radioButton_219.toggled.connect(lambda: self.answer_changed(self.radioButton_219))
        self.radioButton_220.toggled.connect(lambda: self.answer_changed(self.radioButton_220))



class FeatureVectorCalculations:
    def __init__(self, answers):
        self.hash_table = {}
        self.answers = answers
        self.match_features()
        self.feature_vector = self.calculate_feature_vector()

    def match_features(self):
        with open("map.txt") as map_file:
            lines = map_file.readlines() # Satır okunur
            for line in lines:
                oznitelik = line.split("-")[0] # "-" işaretinden öncesi öznitelikleri ifade eder.
                sorular = line.split("-")[1] # "-" işaretinden sonrası öznitelikleri ifade ettiği soruları içerir.
                sorular  = (sorular[0:len(sorular)-1]).split(",") # \n atildi
                sorular = list(map(int, sorular))
                self.hash_table[oznitelik] = sorular # "-" Hash table'ye öznitelikler yerleştirilir.

    def calculate_feature_vector(self):
        vector = []
        for key in self.hash_table.keys():
            avg = 0
            for question in self.hash_table[key]:
                x = int(self.answers[question - 1])
                if x != -1:
                    avg += self.answers[question - 1]
            avg = avg / len(self.hash_table[key])
            vector.append(avg)
        # print("vector", vector)
        return vector

    def get_hash_table(self):
        return self.feature_vector


class Models:
    def __init__ (self, X, y, ratio):
        ratio = int(ratio)/100
        if ratio == 0.6:
            self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size=0.4, random_state=42)
        elif ratio == 0.7:
            self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size=0.3, random_state=42)
        elif ratio == 0.8:
            self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        else:
            self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size=0.1, random_state=42)


    def random_forest(self):
        self.clf = RandomForestClassifier(max_depth=3, random_state=0)
        accuracy, precision, recall, f1, fbeta = self.return_metrics()
        return self.clf, accuracy, precision, recall, f1, fbeta, self.X_train, self.X_test, self.y_train, self.y_test

    def decision_tree(self):
        self.clf = DecisionTreeClassifier(random_state=42)
        accuracy, precision, recall, f1, fbeta = self.return_metrics()
        return self.clf, accuracy, precision, recall, f1, fbeta, self.X_train, self.X_test, self.y_train, self.y_test

    def k_neighbour(self):
        self.clf = KNeighborsClassifier(n_neighbors=3)
        accuracy, precision, recall, f1, fbeta = self.return_metrics()
        return self.clf, accuracy, precision, recall, f1, fbeta, self.X_train, self.X_test, self.y_train, self.y_test

    def svm(self):
        self.clf = svm.SVC()
        accuracy, precision, recall, f1, fbeta = self.return_metrics()
        return self.clf, accuracy, precision, recall, f1, fbeta, self.X_train, self.X_test, self.y_train, self.y_test

    def logistic_regression(self):
        self.clf = LogisticRegression()
        accuracy, precision, recall, f1, fbeta = self.return_metrics()
        return self.clf, accuracy, precision, recall, f1, fbeta, self.X_train, self.X_test, self.y_train, self.y_test

    def return_random_forest_model(self):
        clf = RandomForestClassifier(max_depth=15, random_state=0)
        return clf

    def return_decision_tree_model(self):
        clf = DecisionTreeClassifier(random_state=42)
        return clf

    def return_k_neighbour_model(self):
        clf = KNeighborsClassifier(n_neighbors=3)
        return clf

    def return_svm_model(self):
        clf = svm.SVC()
        return clf

    def return_logistic_regression_model(self):
        clf = LogisticRegression()
        return clf

    def return_metrics(self):
        self.clf.fit(self.X_train, self.y_train)
        y_pred = self.clf.predict(self.X_test)
        accuracy = accuracy_score(self.y_test, y_pred)
        precision = precision_score(self.y_test, y_pred, average='macro')
        recall = recall_score(self.y_test, y_pred, average='macro')
        f1 = f1_score(self.y_test, y_pred, average='macro')
        fbeta = fbeta_score(self.y_test, y_pred, beta=0.5, average='macro')
        return accuracy, precision, recall, f1, fbeta

    def return_dataset(self):
        return self.X_train, self.X_test, self.y_train, self.y_test

class Read_Dataset:
    def __init__(self, dataset_name):
        if dataset_name == "Dataset.csv":
            # data = pd.read_csv("veri_seti_psiko.csv")
            print(os.getcwd())

            data = pd.read_csv("veri_seti_psiko.csv")
            # data = pd.read_csv("C:/Users/erend/depo/veri_seti_psiko_unified.csv")

        X = data.drop("kredi_riski", axis=1)
        y = data["kredi_riski"]
        questions = X.values.tolist()
        self.targets = y.values.tolist()

        self.feature_vector_array = []
        for question in questions:
            vector_class = FeatureVectorCalculations(question)
            feature_vector = vector_class.get_hash_table()
            self.feature_vector_array.append(feature_vector)

    def get_dataset(self):
        return self.feature_vector_array, self.targets



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        self.radio_choice = -1 # 0 ise cross-validation, 1 ise split
        self.train = "70"
        self.dataset_choice = ""
        self.algorithm_choice = ""
        self.selected_algorithm = ""
        self.answers = []
        self.is_dataset_initialized = False
        self.is_algorithm_initialized = False
        
        Dialog.setObjectName("Dialog")
        Dialog.resize(1311, 656)
        Dialog.setStyleSheet("border-top-color: rgb(85, 255, 0);")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(0, -50, 1311, 711))
        self.frame_3.setStyleSheet("background-color: white;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(930, 80, 361, 591))
        self.frame_4.setStyleSheet("background-color: white;\n"
"border: 3px solid black;\n"
"border-radius: 15px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setLineWidth(3)
        self.frame_4.setMidLineWidth(5)
        self.frame_4.setObjectName("frame_4")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(130, 30, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border: 0px solid white")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(30, 70, 121, 31))
        self.label_11.setStyleSheet("border: 0px solid white")
        self.label_11.setObjectName("label_11")
        self.instance_value = QtWidgets.QLabel(self.frame_4)
        self.instance_value.setGeometry(QtCore.QRect(270, 70, 121, 31))
        self.instance_value.setStyleSheet("border: 0px solid white")
        self.instance_value.setObjectName("instance_value")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setGeometry(QtCore.QRect(30, 100, 121, 31))
        self.label_13.setStyleSheet("border: 0px solid white")
        self.label_13.setObjectName("label_13")
        self.instance_yes = QtWidgets.QLabel(self.frame_4)
        self.instance_yes.setGeometry(QtCore.QRect(270, 100, 121, 31))
        self.instance_yes.setStyleSheet("border: 0px solid white")
        self.instance_yes.setObjectName("instance_yes")
        self.instance_no = QtWidgets.QLabel(self.frame_4)
        self.instance_no.setGeometry(QtCore.QRect(270, 130, 121, 31))
        self.instance_no.setStyleSheet("border: 0px solid white")
        self.instance_no.setObjectName("instance_no")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(30, 130, 121, 31))
        self.label_16.setStyleSheet("border: 0px solid white")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(30, 200, 121, 31))
        self.label_17.setStyleSheet("border: 0px solid white")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setGeometry(QtCore.QRect(30, 230, 121, 31))
        self.label_18.setStyleSheet("border: 0px solid white")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(130, 170, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("border: 0px solid white")
        self.label_19.setObjectName("label_19")
        self.train_no = QtWidgets.QLabel(self.frame_4)
        self.train_no.setGeometry(QtCore.QRect(270, 260, 121, 31))
        self.train_no.setStyleSheet("border: 0px solid white")
        self.train_no.setObjectName("train_no")
        self.label_21 = QtWidgets.QLabel(self.frame_4)
        self.label_21.setGeometry(QtCore.QRect(30, 260, 121, 31))
        self.label_21.setStyleSheet("border: 0px solid white")
        self.label_21.setObjectName("label_21")
        self.train_value = QtWidgets.QLabel(self.frame_4)
        self.train_value.setGeometry(QtCore.QRect(270, 200, 121, 31))
        self.train_value.setStyleSheet("border: 0px solid white")
        self.train_value.setObjectName("train_value")
        self.train_yes = QtWidgets.QLabel(self.frame_4)
        self.train_yes.setGeometry(QtCore.QRect(270, 230, 121, 31))
        self.train_yes.setStyleSheet("border: 0px solid white")
        self.train_yes.setObjectName("train_yes")
        self.label_24 = QtWidgets.QLabel(self.frame_4)
        self.label_24.setGeometry(QtCore.QRect(30, 330, 121, 31))
        self.label_24.setStyleSheet("border: 0px solid white")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_4)
        self.label_25.setGeometry(QtCore.QRect(30, 360, 121, 31))
        self.label_25.setStyleSheet("border: 0px solid white")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        self.label_26.setGeometry(QtCore.QRect(130, 300, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("border: 0px solid white")
        self.label_26.setObjectName("label_26")
        self.test_no = QtWidgets.QLabel(self.frame_4)
        self.test_no.setGeometry(QtCore.QRect(270, 390, 121, 31))
        self.test_no.setStyleSheet("border: 0px solid white")
        self.test_no.setObjectName("test_no")
        self.label_28 = QtWidgets.QLabel(self.frame_4)
        self.label_28.setGeometry(QtCore.QRect(30, 390, 121, 31))
        self.label_28.setStyleSheet("border: 0px solid white")
        self.label_28.setObjectName("label_28")
        self.test_value = QtWidgets.QLabel(self.frame_4)
        self.test_value.setGeometry(QtCore.QRect(270, 330, 121, 31))
        self.test_value.setStyleSheet("border: 0px solid white")
        self.test_value.setObjectName("test_value")
        self.test_yes = QtWidgets.QLabel(self.frame_4)
        self.test_yes.setGeometry(QtCore.QRect(270, 360, 121, 31))
        self.test_yes.setStyleSheet("border: 0px solid white")
        self.test_yes.setObjectName("test_yes")
        self.label_31 = QtWidgets.QLabel(self.frame_4)
        self.label_31.setGeometry(QtCore.QRect(30, 490, 121, 31))
        self.label_31.setStyleSheet("border: 0px solid white")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_4)
        self.label_32.setGeometry(QtCore.QRect(130, 430, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("border: 0px solid white")
        self.label_32.setObjectName("label_32")
        self.results_no = QtWidgets.QLabel(self.frame_4)
        self.results_no.setGeometry(QtCore.QRect(270, 490, 121, 31))
        self.results_no.setStyleSheet("border: 0px solid white")
        self.results_no.setObjectName("results_no")
        self.results_yes = QtWidgets.QLabel(self.frame_4)
        self.results_yes.setGeometry(QtCore.QRect(270, 460, 121, 31))
        self.results_yes.setStyleSheet("border: 0px solid white")
        self.results_yes.setObjectName("results_yes")
        self.label_35 = QtWidgets.QLabel(self.frame_4)
        self.label_35.setGeometry(QtCore.QRect(30, 460, 121, 31))
        self.label_35.setStyleSheet("border: 0px solid white")
        self.label_35.setObjectName("label_35")
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        self.label_12.setGeometry(QtCore.QRect(330, 10, 47, 591))
        self.label_12.setStyleSheet("border: 0px solid white")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("white.png"))
        self.label_12.setObjectName("label_12")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(410, 80, 521, 591))
        self.frame_2.setStyleSheet("border: 3px solid black;\n"
"border-radius: 15px;\n"
"background-color: white;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(5)
        self.frame_2.setMidLineWidth(5)
        self.frame_2.setObjectName("frame_2")
        self.dataset_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.dataset_comboBox.setGeometry(QtCore.QRect(170, 40, 151, 31))
        self.dataset_comboBox.setStyleSheet("border-radius: 3px;\n"
"border-width: 1px;\n"
"background-color: lightgray;\n"
"color: black;")
        self.dataset_comboBox.setObjectName("dataset_comboBox")
        self.dataset_comboBox.addItem("")
        self.dataset_comboBox.addItem("")
        self.dataset_comboBox.currentIndexChanged.connect(self.on_dataset_selection_changed)

        self.algorithm_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.algorithm_comboBox.setGeometry(QtCore.QRect(170, 120, 151, 31))
        self.algorithm_comboBox.setStyleSheet("border-radius: 3px;\n"
"border-width: 1px;\n"
"background-color: lightgray;\n"
"color: black;")
        self.algorithm_comboBox.setObjectName("algorithm_comboBox")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.addItem("")
        self.algorithm_comboBox.setDisabled(True)
        self.algorithm_comboBox.currentIndexChanged.connect(self.on_algorithm_selection_changed)

        self.cross_val_radio = QtWidgets.QRadioButton(self.frame_2)
        self.cross_val_radio.setGeometry(QtCore.QRect(190, 200, 111, 17))
        self.cross_val_radio.setStyleSheet("border-color: none;")
        self.cross_val_radio.setObjectName("cross_val_radio")
        self.cross_val_radio.clicked.connect(self.cross_radio_choice)

        self.persentage_spl_radio = QtWidgets.QRadioButton(self.frame_2)
        self.persentage_spl_radio.setGeometry(QtCore.QRect(190, 260, 111, 21))
        self.persentage_spl_radio.setStyleSheet("border-color: none;")
        self.persentage_spl_radio.setObjectName("persentage_spl_radio")
        self.persentage_spl_radio.clicked.connect(self.percentage_radio_choice)

        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(170, 310, 151, 31))
        self.pushButton_5.setStyleSheet("border :3px solid black;\n"
"background-color: lightgray;\n"
"border-color: gray;\n"
"border-width: 2px;\n"
"color: black;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.recall_value = QtWidgets.QFrame(self.frame_2)
        self.recall_value.setGeometry(QtCore.QRect(40, 380, 451, 131))
        self.recall_value.setStyleSheet("border: 3px solid black;\n"
"border-radius: 25px;\n"
"background-color: lightgrey;")
        self.recall_value.setFrameShape(QtWidgets.QFrame.Panel)
        self.recall_value.setFrameShadow(QtWidgets.QFrame.Plain)
        self.recall_value.setLineWidth(5)
        self.recall_value.setMidLineWidth(5)
        self.recall_value.setObjectName("recall_value")
        self.label_3 = QtWidgets.QLabel(self.recall_value)
        self.label_3.setGeometry(QtCore.QRect(130, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 0px;\n"
"color: black;")
        self.label_3.setObjectName("label_3")
        self.accuracy_value = QtWidgets.QLabel(self.recall_value)
        self.accuracy_value.setGeometry(QtCore.QRect(50, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.accuracy_value.setFont(font)
        self.accuracy_value.setStyleSheet("border: 0px;\n"
"color: black;")
        self.accuracy_value.setObjectName("accuracy_value")
        self.label_4 = QtWidgets.QLabel(self.recall_value)
        self.label_4.setGeometry(QtCore.QRect(240, 30, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: 0px;\n"
"color: black;")
        self.label_4.setObjectName("label_4")
        self.precision_value = QtWidgets.QLabel(self.recall_value)
        self.precision_value.setGeometry(QtCore.QRect(160, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.precision_value.setFont(font)
        self.precision_value.setStyleSheet("border: 0px;\n"
"color: black;")
        self.precision_value.setObjectName("precision_value")
        self.label_2 = QtWidgets.QLabel(self.recall_value)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: 0px;\n"
"color: black;")
        self.label_2.setObjectName("label_2")
        self.f1_value = QtWidgets.QLabel(self.recall_value)
        self.f1_value.setGeometry(QtCore.QRect(350, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.f1_value.setFont(font)
        self.f1_value.setStyleSheet("border: 0px;\n"
"color: black;")
        self.f1_value.setObjectName("f1_value")
        self.label_5 = QtWidgets.QLabel(self.recall_value)
        self.label_5.setGeometry(QtCore.QRect(330, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: 0px;\n"
"color: black;")
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.recall_value)
        self.label_8.setGeometry(QtCore.QRect(260, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border: 0px;\n"
"color: black;")
        self.label_8.setObjectName("label_8")
        self.train_ratio = QtWidgets.QLineEdit(self.frame_2)
        self.train_ratio.setGeometry(QtCore.QRect(340, 200, 51, 31))
        self.train_ratio.setStyleSheet("border: 2px solid black; border-radius: 0px;")
        self.train_ratio.setText("")
        self.train_ratio.setPlaceholderText("")
        self.train_ratio.setObjectName("train_ratio")
        self.train_ratio.textChanged.connect(self.train_ratio_changed)

        self.test_ratio = QtWidgets.QLabel(self.frame_2)
        self.test_ratio.setGeometry(QtCore.QRect(340, 250, 51, 31))
        self.test_ratio.setStyleSheet("border: 2px solid black; border-radius: 0px;")
        self.test_ratio.setText("")
        self.test_ratio.setObjectName("test_ratio")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(420, 200, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: 0px solid black; border-radius: 0px;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(420, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border: 0px solid black; border-radius: 0px;")
        self.label_7.setObjectName("label_7")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setGeometry(QtCore.QRect(10, 80, 401, 591))
        self.frame.setStyleSheet("border: 3px solid black;\n"
"border-radius: 15px;\n"
"background-color: white;")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(5)
        self.frame.setMidLineWidth(5)
        self.frame.setObjectName("frame")
        self.over_samp_button = QtWidgets.QPushButton(self.frame)
        self.over_samp_button.setGeometry(QtCore.QRect(100, 360, 201, 31))
        self.over_samp_button.setStyleSheet("border :3px solid black;\n"
"background-color: lightgray;\n"
"border-color: gray;\n"
"border-width: 2px;\n"
"color: black;")
        self.over_samp_button.setDefault(False)
        self.over_samp_button.setFlat(False)
        self.over_samp_button.setObjectName("over_samp_button")
        self.under_samp_button = QtWidgets.QPushButton(self.frame)
        self.under_samp_button.setGeometry(QtCore.QRect(100, 430, 201, 31))
        self.under_samp_button.setStyleSheet("border :3px solid black;\n"
"background-color: lightgray;\n"
"border-color: gray;\n"
"border-width: 2px;\n"
"color: black;")
        self.under_samp_button.setDefault(False)
        self.under_samp_button.setFlat(False)
        self.under_samp_button.setObjectName("under_samp_button")
        self.reset = QtWidgets.QPushButton(self.frame)
        self.reset.setGeometry(QtCore.QRect(160, 490, 71, 71))
        self.reset.setStyleSheet("border :3px solid red;\n"
"background-color: red;\n"
"border-radius: 35px;\n"
"color: white;")
        self.reset.setDefault(False)
        self.reset.setFlat(False)
        self.reset.setObjectName("reset")
        self.graphics = QtWidgets.QLabel(self.frame)
        self.graphics.setGeometry(QtCore.QRect(40, 30, 311, 291))
        self.graphics.setText("")
        # self.graphics.setPixmap(QtGui.QPixmap("bar_grafik.png"))
        self.graphics.setObjectName("graphics")
        self.graphics.setStyleSheet("border: 2px solid black;")

        self.credit_risk_button = QtWidgets.QPushButton(self.frame_2)
        self.credit_risk_button.setGeometry(QtCore.QRect(180, 530, 151, 31))
        self.credit_risk_button.setStyleSheet("border :3px solid black;\n"
"background-color: rgb(170, 170, 255);\n"
"border-color: gray;\n"
"border-width: 2px;\n"
"color: black;")
        self.credit_risk_button.setObjectName("credit_risk_button")
        self.credit_risk_button.clicked.connect(self.newWindow)

        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(-20, 10, 47, 591))
        self.label_9.setStyleSheet("border: 0px solid white")
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("white.png"))
        self.label_9.setObjectName("label_9")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(10, 60, 1281, 31))
        self.label.setStyleSheet("border: 3px solid grey;\n"
"background-color: lightgray;\n"
"")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def newWindow(self):
        if self.is_dataset_initialized == True and self.is_algorithm_initialized == True:    
            # print("newwindpw")
            Dialog = QtWidgets.QDialog()
            ui = Sorular()
            ui.setupUi(Dialog, self.clf)
            Dialog.show()
            Dialog.exec_()
        else:
            self.show_error_message()


    def train_ratio_changed(self):
        self.train = self.train_ratio.text()
        try:
            self.test = str(100 - int(self.train))
        except Exception:
            test = ""

        self.test_ratio.setText(self.test)

    def on_algorithm_selection_changed(self, index):
        self.selected_algorithm = self.algorithm_comboBox.currentText()
        if self.selected_algorithm != "Algoritma Seçiniz":
            self.is_algorithm_initialized = True
        else:
            self.is_algorithm_initialized = False



    def cross_radio_choice(self):
        self.train_ratio.setDisabled(True)
        self.radio_choice = 0
        self.train_ratio.setText("")
        self.train = 0


    def percentage_radio_choice(self):
        self.radio_choice = 1
        self.train_ratio.setDisabled(False)


    def on_dataset_selection_changed(self):
        low=0
        high=0
        selected_item = self.dataset_comboBox.currentText()
        self.algorithm_comboBox.setDisabled(False)
        # print("Seçilen öğe:", self.dataset_choice)
        if selected_item != "Veri Setini Seçiniz":
            self.dataset_choice = selected_item
            obj = Read_Dataset(self.dataset_choice)
            self.dataset, self.targets = obj.get_dataset()
            total = len(self.targets)
            low = self.targets.count(0)
            high = self.targets.count(1)
            self.is_dataset_initialized = True

            self.get_bar_graph(total, low, high)
            # print(len(self.dataset), len(self.targets))
        else:
            self.is_dataset_initialized = False

        self.graphics.setPixmap(QtGui.QPixmap("bar_grafik.png"))


    def get_bar_graph(self, total, low, high):

        veri = {"Total": total, "Low Risk": low, "High Risk": high}
        colors = [(0,0,0), (0,1,1), (1,0,0)]
        plt.figure(figsize=(3, 3))
        plt.bar(veri.keys(), veri.values(), color=colors)
        # plt.bar()
        plt.savefig("bar_grafik.png", format="png")
        self.graphics.setPixmap(QtGui.QPixmap(r"bar_grafik.png"))


    def train_data(self):

        if self.selected_algorithm != "" and self.selected_algorithm != "Algoritma Seçiniz":
            if self.radio_choice == 0: # Cross Validation ise
                self.train = 0.7 # cross validation seçilmişse, eğitim için defaul olarak 0.7 eğitim oranı girilir
            models = Models(self.dataset, self.targets, self.train)
            choice = -1 # 0 ise cross-validation, 1 ise percentage split
            if self.radio_choice == 0: # Cross Validation ise

                if self.selected_algorithm == "Random Forest":
                    clf = models.return_random_forest_model()
                elif self.selected_algorithm == "Decision Tree":
                    clf = models.return_decision_tree_model()

                elif self.selected_algorithm == "KNN":
                    clf = models.return_k_neighbour_model()

                elif self.selected_algorithm == "SVM":
                    clf = models.return_svm_model()

                elif self.selected_algorithm == "Logistic Regression":
                    clf = models.return_logistic_regression_model()

                accuracy = cross_val_score(clf, self.dataset, self.targets, cv=10, scoring='accuracy')  
                precision = cross_val_score(clf, self.dataset, self.targets, cv=10, scoring='precision')  
                recall = cross_val_score(clf, self.dataset, self.targets, cv=10, scoring='recall')  
                f1 = cross_val_score(clf, self.dataset, self.targets, cv=10, scoring='f1')  

                self.metrics = [accuracy.mean(), precision.mean(), recall.mean(), f1.mean()]

                choice = 0
                # print("Ortalama skor:", accuracy.mean())
                self.X_train, self.X_test, self.y_train, self.y_test = models.return_dataset()

            else: # Percentage ise
                if self.selected_algorithm == "Random Forest":
                    clf, accuracy, precision, recall, f1, fbeta, self.X_train, self.X_test, self.y_train, self.y_test = models.random_forest()
                elif self.selected_algorithm == "Decision Tree":
                    clf, accuracy, precision, recall, f1, fbeta, self.X_train, self.X_test, self.y_train, self.y_test = models.decision_tree()

                elif self.selected_algorithm == "KNN":
                    clf, accuracy, precision, recall, f1, fbeta, self.X_train, self.X_test, self.y_train, self.y_test = models.k_neighbour()

                elif self.selected_algorithm == "SVM":
                    clf, accuracy, precision, recall, f1, fbeta, self.X_train, self.X_test, self.y_train, self.y_test = models.svm()

                elif self.selected_algorithm == "Logistic Regression":
                    clf, accuracy, precision, recall, f1, fbeta, self.X_train, self.X_test, self.y_train, self.y_test = models.logistic_regression()

                self.metrics = [str(accuracy)[0:5], str(precision)[0:5], str(recall)[0:5], str(f1)[0:5], str(fbeta)[0:5]]
                choice = 1
                self.clf = clf

            self.accuracy_value.setText(str(self.metrics[0])[:5])
            self.precision_value.setText(str(self.metrics[1])[:5])
            self.label_8.setText(str(self.metrics[2])[:5])
            self.f1_value.setText(str(self.metrics[3])[:5])

            self.setResultDetails(choice)
        else:
            self.show_error_message()

    def setResultDetails(self, cross_or_perc):
        self.instance_value.setText(str(len(self.targets)))
        self.instance_yes.setText(str(self.targets.count(0)))
        self.instance_no.setText(str(self.targets.count(1)))

        if cross_or_perc == 0:
            train_value_count = len(self.X_train)
            self.train_value.setText(str(train_value_count))
            self.train_yes.setDisabled(True)
            self.train_no.setDisabled(True)
            # self.train_no.setText(str(self.y_train.count(1)))

            test_value_count = len(self.X_test)
            self.test_value.setText(str(test_value_count))
            self.test_yes.setDisabled(True)
            self.test_no.setDisabled(True)

            self.results_yes.setText("0")
            self.results_no.setText("0")
            self.results_yes.setDisabled(True)
            self.results_no.setDisabled(True)


        elif cross_or_perc == 1:
            train_value_count = len(self.X_train)
            self.train_value.setText(str(train_value_count))
            self.train_yes.setDisabled(False)
            self.train_no.setDisabled(False)
            self.train_yes.setText(str(self.y_train.count(0)))
            self.train_no.setText(str(self.y_train.count(1)))

            test_value_count = len(self.X_test)
            self.test_value.setText(str(test_value_count))
            self.test_yes.setDisabled(False)
            self.test_no.setDisabled(False)
            self.test_yes.setText(str(self.y_test.count(0)))
            self.test_no.setText(str(self.y_test.count(1)))

            self.results_yes.setDisabled(False)
            self.results_no.setDisabled(False)
            yes_count = round(float(self.metrics[0]) * len(self.y_test))
            no_count = len(self.y_test) - yes_count
            self.results_yes.setText(str(yes_count))
            self.results_no.setText(str(no_count))

    def show_error_message(self):
        new_window = QMainWindow()
        new_window.setWindowTitle("Yeni Pencere")
        new_window.setGeometry(730, 480, 548, 50)
        
        message_box = QMessageBox(new_window)
        message_box.setStyleSheet("padding-right: 20px")
        message_box.setText("Algoritma veya veri seti seçimi boş bırakılamaz.")
        message_box.exec_()


    def over_sampling_click(self):
        try:  
            ros = RandomOverSampler(random_state=0)
            X_resampled, y_resampled = ros.fit_resample(self.dataset, self.targets)
            self.dataset = X_resampled
            self.targets = y_resampled

            total = len(self.targets)
            low = self.targets.count(0)
            high = self.targets.count(1)

            self.get_bar_graph(total, low, high)
        except Exception as e:
            self.show_error_message()

    def under_sampling_click(self):
        try:
            ros = RandomUnderSampler(random_state=0)
            X_resampled, y_resampled = ros.fit_resample(self.dataset, self.targets)

            self.dataset = X_resampled
            self.targets = y_resampled

            total = len(self.targets)
            low = self.targets.count(0)
            high = self.targets.count(1)

            self.get_bar_graph(total, low, high)
        except Exception:
            self.show_error_message()

    def reset_clicked(self):
        obj = Read_Dataset(self.dataset_choice)
        self.dataset, self.targets = obj.get_dataset()
        total = len(self.targets)
        low = self.targets.count(0)
        high = self.targets.count(1)
        self.get_bar_graph(total, low, high)  


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_10.setText(_translate("Dialog", "Instance Details"))
        self.label_11.setText(_translate("Dialog", "Instance"))
        self.instance_value.setText(_translate("Dialog", "0"))
        self.label_13.setText(_translate("Dialog", "Low Credit Risk"))
        self.instance_yes.setText(_translate("Dialog", "0"))
        self.instance_no.setText(_translate("Dialog", "0"))
        self.label_16.setText(_translate("Dialog", "High Credit Risk"))
        self.label_17.setText(_translate("Dialog", "Train"))
        self.label_18.setText(_translate("Dialog", "Low Credit Risk"))
        self.label_19.setText(_translate("Dialog", "Train Details"))
        self.train_no.setText(_translate("Dialog", "0"))
        self.label_21.setText(_translate("Dialog", "High Credit Risk"))
        self.train_value.setText(_translate("Dialog", "0"))
        self.train_yes.setText(_translate("Dialog", "0"))
        self.label_24.setText(_translate("Dialog", "Test"))
        self.label_25.setText(_translate("Dialog", "Low Credit Risk"))
        self.label_26.setText(_translate("Dialog", "Test Details"))
        self.test_no.setText(_translate("Dialog", "0"))
        self.label_28.setText(_translate("Dialog", "High Credit Risk"))
        self.test_value.setText(_translate("Dialog", "0"))
        self.test_yes.setText(_translate("Dialog", "0"))
        self.label_31.setText(_translate("Dialog", "False"))
        self.label_32.setText(_translate("Dialog", "Test Results"))
        self.results_no.setText(_translate("Dialog", "0"))
        self.results_yes.setText(_translate("Dialog", "0"))
        self.label_35.setText(_translate("Dialog", "True"))
        self.dataset_comboBox.setItemText(0, _translate("Dialog", "Veri Setini Seçiniz"))
        self.dataset_comboBox.setItemText(1, _translate("Dialog", "Dataset.csv"))
        self.algorithm_comboBox.setItemText(0, _translate("Dialog", "Algoritma Seçiniz"))
        self.algorithm_comboBox.setItemText(1, _translate("Dialog", "KNN"))
        self.algorithm_comboBox.setItemText(2, _translate("Dialog", "SVM"))
        self.algorithm_comboBox.setItemText(3, _translate("Dialog", "Logistic Regression"))
        self.algorithm_comboBox.setItemText(4, _translate("Dialog", "Decision Tree"))
        self.algorithm_comboBox.setItemText(5, _translate("Dialog", "Random Forest"))
        self.cross_val_radio.setText(_translate("Dialog", "Cross Validation"))
        self.persentage_spl_radio.setText(_translate("Dialog", "Percentage Split"))
        self.pushButton_5.setText(_translate("Dialog", "Run!"))
        self.pushButton_5.clicked.connect(self.train_data)

        self.credit_risk_button.setText("Predict Credit Score")


        self.label_3.setText(_translate("Dialog", "Precision"))
        self.accuracy_value.setText(_translate("Dialog", "0"))
        self.label_4.setText(_translate("Dialog", "Recall"))
        self.precision_value.setText(_translate("Dialog", "0"))
        self.label_2.setText(_translate("Dialog", "Accuracy"))
        self.f1_value.setText(_translate("Dialog", "0"))
        self.label_5.setText(_translate("Dialog", "F1 Score"))
        self.label_8.setText(_translate("Dialog", "0"))
        self.label_6.setText(_translate("Dialog", "Train"))
        self.label_7.setText(_translate("Dialog", "Test"))
        self.over_samp_button.setText(_translate("Dialog", "Random Over Sampling"))
        self.over_samp_button.clicked.connect(self.over_sampling_click)

        self.under_samp_button.setText(_translate("Dialog", "Random Under Sampling"))
        self.under_samp_button.clicked.connect(self.under_sampling_click)

        self.reset.setText(_translate("Dialog", "RESET"))
        self.reset.clicked.connect(self.reset_clicked)

        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Credit Risk Prediction via Psychometric Tests</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
